# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Haunto"
email: "haunto.aid@gmail.com"
description: ""
domain: haunt-o.github.io
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://haunt-o.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  Haunt-o

# Build settings
# theme: "jekyll-theme-cayman"
# theme: minima
# theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme
plugins:
  - jekyll-remote-theme
  - jekyll-feed

repository: haunt-o/haunt-o.github.io

# BULMA SETTINGS
paginate: 5
paginate_path: "/blog/page:num"
fixed_navbar: top

defaults:
  -
    scope:
      path: ""
    values:
      layout: page
      hero_image: ../images/haunto_home_banner.jpg
      hero_height: is-small